"""esquema inicial

Revision ID: 8ff28e7da4d6
Revises: 
Create Date: 2026-07-07 01:11:02.213409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff28e7da4d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preguntas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usuarios_username_lower', 'usuarios', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('opciones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pregunta_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.SmallInteger(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.CheckConstraint('numero IN (1, 2)', name='ck_opciones_numero'),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pregunta_id', 'numero', name='uq_opciones_pregunta_numero')
    )
    op.create_table('salas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('estado', sa.Enum('esperando', 'en_curso', 'finalizada', name='estado_sala_enum'), server_default='esperando', nullable=False),
    sa.Column('anfitrion_id', sa.UUID(), nullable=False),
    sa.Column('turno_actual', sa.Integer(), server_default='0', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anfitrion_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salas_codigo'), 'salas', ['codigo'], unique=True)
    op.create_table('marcador_historico',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('sala_id', sa.UUID(), nullable=False),
    sa.Column('puntos_finales', sa.Integer(), nullable=False),
    sa.Column('gano', sa.Boolean(), nullable=False),
    sa.Column('finalizada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcador_historico_usuario_id'), 'marcador_historico', ['usuario_id'], unique=False)
    op.create_table('rondas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sala_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.UUID(), nullable=False),
    sa.Column('lector_id', sa.UUID(), nullable=False),
    sa.Column('prediccion', sa.Enum('mayoria_1', 'todos_1', 'mayoria_2', 'todos_2', name='prediccion_enum'), nullable=True),
    sa.Column('estado', sa.Enum('leyendo', 'votando', 'resuelta', name='estado_ronda_enum'), server_default='leyendo', nullable=False),
    sa.Column('resultado', sa.Enum('mayoria_1', 'todos_1', 'mayoria_2', 'todos_2', 'empate', name='resultado_enum'), nullable=True),
    sa.Column('acierto', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lector_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rondas_sala_id'), 'rondas', ['sala_id'], unique=False)
    op.create_table('sala_jugadores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sala_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('orden_turno', sa.SmallInteger(), nullable=True),
    sa.Column('puntos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('conectado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('unido_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sala_id', 'usuario_id', name='uq_sala_jugadores_sala_usuario')
    )
    op.create_table('votos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ronda_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('opcion', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('opcion IN (1, 2)', name='ck_votos_opcion'),
    sa.ForeignKeyConstraint(['ronda_id'], ['rondas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ronda_id', 'usuario_id', name='uq_votos_ronda_usuario')
    )
    op.create_index(op.f('ix_votos_ronda_id'), 'votos', ['ronda_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votos_ronda_id'), table_name='votos')
    op.drop_table('votos')
    op.drop_table('sala_jugadores')
    op.drop_index(op.f('ix_rondas_sala_id'), table_name='rondas')
    op.drop_table('rondas')
    op.drop_index(op.f('ix_marcador_historico_usuario_id'), table_name='marcador_historico')
    op.drop_table('marcador_historico')
    op.drop_index(op.f('ix_salas_codigo'), table_name='salas')
    op.drop_table('salas')
    op.drop_table('opciones')
    op.drop_index('ix_usuarios_username_lower', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('preguntas')
    # ### end Alembic commands ###
    sa.Enum(name='resultado_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='estado_ronda_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='prediccion_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='estado_sala_enum').drop(op.get_bind(), checkfirst=True)
